Repository seqan/seqan, pull requests merged in 2018-10, with the labels that each got.

#2312 [DOX] Fix documentation of writeRecords function for Graphs.
  include/seqan/graph_types/graph_drawing.h
  manual/source/Tutorial/DataStructures/Graphs.rst
Labels: dox

#2351 [DOC] Updates the find_base.h file to use the example from finder_onl…
  include/seqan/find/find_base.h
Labels: dox

#2302 [FIX] Bidirectional FM Index: goDownString pushing too many states on…
  include/seqan/index/index_bidirectional_stree.h
  include/seqan/index/index_bifm_stree.h
  include/seqan/index/index_esa_stree.h
  tests/index/test_index_stree_iterators.cpp
  tests/index/test_stree_iterators.h
Labels: bug

#2355 [FIX-#2346] correct BED12 file parsing, compatible with UCSC
  include/seqan/bed_io/read_bed.h
  tests/bed_io/test_bed_io.cpp
Labels: bug

#2326 directly building test cases with g++ fails
  include/seqan/basic/debug_test_system.h
Labels: bug

#2354 [FIX] Some typos and adding include modules.
  demos/tutorial/simple_genome_alignment/lagan.cpp
  manual/source/Tutorial/HowTo/UseCases/SimpleGenomeAlignment.rst
Labels: ready to merge
