Repository seqan/seqan, pull requests merged in 2018-11, with the labels that each got.

#2357 [FIX] GCC8 Warning
  include/seqan/basic/iterator_adaptor.h
Labels: compiler-warning

#2285 [INTERNAL] Fix ctd output: add ctdVersion tag in header.
  include/seqan/arg_parse/arg_parse_ctd_support.h
  tests/arg_parse/test_app.ctd
Labels: bug

#2286 Infrastructure adds automatic testing of correct ctd export of our tools
  apps/alf/CMakeLists.txt
  apps/bs_tools/CMakeLists.txt
  apps/dfi/CMakeLists.txt
  apps/fiona/CMakeLists.txt
  apps/fx_tools/CMakeLists.txt
  apps/insegt/CMakeLists.txt
  apps/mason2/CMakeLists.txt
  apps/rabema/CMakeLists.txt
  apps/razers3/CMakeLists.txt
  apps/sak/CMakeLists.txt
  apps/sam2matrix/CMakeLists.txt
  apps/samcat/CMakeLists.txt
  apps/seqan_tcoffee/CMakeLists.txt
  apps/snp_store/CMakeLists.txt
  apps/stellar/CMakeLists.txt
  apps/tree_recon/CMakeLists.txt
  apps/yara/CMakeLists.txt
  util/cmake/SeqAnBuildSystem.cmake
Labels: enhancement

#2361 [FIX-#2360] Initialization of iterators over empty graphs
  include/seqan/graph_types/graph_iterator_edge.h
  include/seqan/graph_types/graph_iterator_outedge.h
  tests/graph_types/test_graph_types_iterators.cpp
Labels: bug
